trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'               # root of your static site
    output_location: ''             # if no build step, leave blank
    azure_static_web_apps_api_token: '$(deployment_token)' # define in pipeline secrets
